name: PointSystem
main: de.lamacraft.pointsystem.main.Main
version: 1.0
api-version: 1.18
commands:
  points:
    description: Der Punkte Command!
  shop:
    description: Öffnet den Shop!
  holo:
    description: Verwaltet die Hologramme!
  maintance:
    description: (De)aktiviert den Wartungsmodus!
  resetwinner:
    description: Setzt den Gewinner zurück!